### ISSUE TITLE
Rebuild PR when target branch gets updated

### ISSUE THREAD

**Issue by rmohta** [Eernie/bitbucket-webhooks-plugin#92] opened 2018-02-09 14:06 UTC
If we have an open PR, let's say `feature/1` to `develop`.  Now imagine, I have updated develop branch either by direct commit or by merging some other PR. 

**What we would have expected?**
Since develop branch was updated, any open PR which would target develop branch should re-build to make sure nothing is broken.

**What we noticed?**
Nothing happened.

Job type setup in Jenkins: Multibranch Pipeline
Atlassian Bitbucket v5.2.3

In Settings page, we have the following Pull Request Events enabled

Pull request created
Pull request updated
Pull request re-opened
Pull request re-scoped
Pull request commented

**Comment by casz** [comment] 2018-02-09 15:02
@rmohta Not happening, this is how bitbucket has intended it to avoid merge checks hell and Jenkins to avoid build hell.

Duplicate of #86 
> No, https://community.atlassian.com/t5/Bitbucket-questions/Change-pull-request-refs-after-Commit-instead-of-after-Approval/qaq-p/194702 answers why it shouldn't be done.

**Closed by casz** 2018-02-09 15:02 UTC
